### ISSUE TITLE
Desktop broken after closing Komorebi Linux Mint 18.2 Sonya

### ISSUE THREAD

**Issue by rinrincodes** [iabem97/komorebi#68]
Whenever I close Komorebi on Linux Mint 18.2 Sonya, my desktop no longer works along with any desktop context menus.

**Comment by rinrincodes** [comment]
Desklets still happen to work but no icons or context menus on the desktop.

**Comment by PombaM** [comment]
Same with Ubuntu 16.04 LTS, right click on desktop does nothing.

**Comment by nikhilw** [comment]
Same here. Even after uninstalling (purge) the issue persists, even after restart. no desktop icons being shown, no right click working, even wallpaper had changed to default. I could set it back from settings but nothing else is working. How do I fix this?

**Comment by nikhilw** [comment]
Hmm.. It seems to be taking control of show-desktop[icons] in a way that is incompatible with the way nemo works or either not giving the control back while exiting. Either way it is breaking even the cinnamon system settings. So even if cinnamon settings show that the desktop and icons are enabled they are actually not.  ```gsettings get org.nemo.desktop show-desktop-icons``` returns ```false```. To enable run: ```gsettings set org.nemo.desktop show-desktop-icons true```. It should work normally after this.

**Comment by karanrajpal14** [comment]
Same here on Ubuntu 17.04. Any suggestions on how to fix this?

**Comment by Romanovg185** [comment]
Have the problem as well, and the fix by nikhilw doesn't work, because `gsettings get org.nemo.desktop show-desktop-icons` returns `true` by default...

**Comment by karanrajpal14** [comment]
For Ubuntu users such as myself and @PombaM, here's a fix:

run this in your terminal, `gsettings get org.gnome.desktop.background show-desktop-icons`
This should restore your desktop back to normal as it did for me. Uninstall the program or disable it's startup just to ensure it doesn't happen again.

Source: [ubuntuforums](https://ubuntuforums.org/showthread.php?t=2225322&s=402196e105a349c19ce12ac26a14d9ab&p=13029222#post13029222)

**Comment by poddardelhi** [comment]
@karanrajpal14 

After running this command I'm still not able to fix the issue.
o/p

gsettings get org.gnome.desktop.background show-desktop-icons
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
false

**Comment by nikhilw** [comment]
@poddardelhi The command @karanrajpal14 has mentioned is a retrieval command, not a setter, it will have no effect; instead if you wish, you should try: ```gsettings set org.gnome.desktop.background show-desktop-icons true```
**Disclaimer**: I have not run the command above, I am not using Ubuntu, I am merely stating the settings modification counterpart for the command mentioned above. If you are using Mint+Cinnamon you should try the command from my post above.

@Romanovg185 Are you using Mint+Cinnamon or Ubuntu? The command in the post is for Mint+Cinnamon. If you are using Ubuntu, try the modified command in this post.

**Comment by karanrajpal14** [comment]
@nikhilw thanks for correcting that. My bad. I've corrected the post. 

@poddardelhi check the edited post and try it out. It should work. It's working fine for me now.

**Comment by poddardelhi** [comment]
@karanrajpal14 

After running the command I'm getting this message
gsettings set org.gnome.desktop.background show-desktop-icons true
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
**Did you also got the same?**

**Comment by poddardelhi** [comment]
I fixed it through graphical.

**do this with graphical program, dconf editor.
You would simply follow the same path as laid out above.
org > gnome > desktop > background > check/uncheck show-desktop-icons**

Thanks @karanrajpal14 and @nikhilw for coming in for help.

Source [https://ubuntuforums.org/showthread.php?t=2246432](url)

**Comment by Romanovg185** [comment]
Fixed it on Mint Cinnamon 18.2 through dconf. I did org > nemo > desktop > show-background-icons. Thanks for the help, especially @poddardelhi !

**Comment by DuMuT6p** [comment]
Issue still persists in Mint Cinnamon 18.2 latest updates with latest komorebi deb package. 

@nikhilw `gsettings set org.nemo.desktop show-desktop-icons true` worked for me, of course with super user privileges. Thank you.

**Comment by karanrajpal14** [comment]
@rinrincodes why close it? Just because we found a hack to fix it doesn't mean the issue has been resolved, right? At the very least, the developers will have to ensure that uninstalling the program doesn't break thing. I suggest you keep this open.

**Comment by rinrincodes** [comment]
I reopened this @karanrajpal14. I thought at first that these hacks were the official solution and that is why I closed it. Thank you for pointing them out tho! ;)

**Comment by NoXoN21** [comment]
`gsettings set org.nemo.desktop show-desktop-icons true` totally fixed desktop after purge komorebi.

**Comment by RobinEd** [comment]
gsettings set org.nemo.desktop show-desktop-icons true

worked without having to purge. Would be great to have this fixed permanently, what an awesome program!

**Comment by Gabrock94** [comment]
Same problem here. "gsettings set org.nemo.desktop show-desktop-icons true" solved for me.
(Mint 18.3 sylvia)

**Comment by AdrienHorgnies** [comment]
When I right click, it crashes my DE (At least I think it's him).
Applying this fix `gsettings set ...` alleviates the problem. Now I have to click several times to trigger the bug T-T.
Any idea where I could get logs about what makes it crash ? I checked most of /var/log but I didn't find anything that seemed related.

**Comment by LinuxOnTheDesktop** [comment]
I had this problem on Mint 19.3 Cinnamon: no normal context menu while the program was installed or indeed after quitting and removing the program. My launcher `ulauncher` stopped working after uninstalling komorebi too.

**Comment by ha7ak3** [comment]
> Hmm.. It seems to be taking control of show-desktop[icons] in a way that is incompatible with the way nemo works. Either that or it is not giving the control back while exiting. Either way it is breaking even the cinnamon system settings. So even if cinnamon settings show that the desktop and icons are enabled they are actually not. `gsettings get org.nemo.desktop show-desktop-icons` returns `false`. To enable run: `gsettings set org.nemo.desktop show-desktop-icons true`. It should work normally after this.

This worked for me. Thanks :+1:

**Comment by ZA0068** [comment]
Its been long time and the dev haven't fixed this issue.

Im sorry but this will take forever.

Just reinstall your linux or if you are smart, go back to previous snapshot where your desktop isn't broken by this malware

**Comment by AddisonSparks** [comment]
Startup applications, create new command, name it whatever you like, use command `nemo-desktop`

I had my desktop disappear even after completely uninstalling Komorebi. For me, a reinstall of Mint would be pretty big, lots of programs.. so I was pretty stubborn and kept looking here and there for some kind of solution. I eventually came across a command to restore nemo. `nemo-desktop`. I used this code for about a year every time I booted the PC until I realized you can use it as a startup command which has worked as a real permanent fix for me.
