### ISSUE TITLE
Komorebi 2.0 not working on Ubuntu 17.10

### ISSUE THREAD

**Issue by awatme** [iabem97/komorebi#99]
I try install komorebi but it not open. I even install manually but both of install ways not working.

**Comment by SHREDDED-WHEAT** [comment]
I just downloaded it and installed it too.  It tries to start but then quits.  Nothing happens.

**Comment by awatme** [comment]
I install /opt/Komorebi via deb package and it's working!

**Comment by czd** [comment]
I installed a fresh install of Ubuntu 17.10 and this is the first program I installed. When I try to launch it shows up in the activity bar but then it closes down again. Is there a way of checking the error log? 
![screenshot from 2018-02-04 13-31-19](https://user-images.githubusercontent.com/1583034/35777539-d43eff54-09af-11e8-9b5c-7d846f96d315.png)

**Comment by t1gu1** [comment]
I try on **Ubuntu 18.04** Alpha 2 and it doesn't work too. :(

**Comment by dansamara** [comment]
Ubuntu 17.10:
`error while loading shared libraries: libgtop-2.0.so.10: cannot open shared object file: No such file or directory`
But Ubuntu has `libgtop` version 2.0.11:
`ldconfig -p | grep libgtop`
`libgtop-2.0.so.11 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.11`

**Comment by sluongng** [comment]
@iabem97 could you please address this?

**Comment by AfrizalFirmansyah** [comment]
![screenshot from 2018-04-09 22-00-16](https://user-images.githubusercontent.com/4180311/38505482-780d958c-3c41-11e8-9173-6697592b6126.png)

open file manager i as root, i use nemo, go to /usr/lib/
search file libgtop-2.0.so.11, click and copy paste, new file like this libgtop-2.0.so (copy).11
rename libgtop-2.0.so (copy).11 to libgtop-2.0.so.10
now open komorebi.

**Comment by Donokami** [comment]
Found out how to deal with this issue in Ubuntu 18.04 (maybe work with 17.10, not tried). All you have to do is create a symbolic link to the gtop library file with this command:
```
sudo ln -s /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.11.0.0 /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.10
```

**Comment by thedonquixotic** [comment]
This really should be fixed. It shouldn't be difficult from what I can tell.

**Comment by thedonquixotic** [comment]
also @awatme  can you please close this thread if your issue has been resolved?

**Comment by iabem97** [comment]
Hello,

Thanks for reporting this issue! `gtop` dependency will be removed in next release. I'll close this issue for now unless it still persists in the next release.

Thanks!

**Comment by AfrizalFirmansyah** [comment]
uwu

**Comment by JordyBlankestijn** [comment]
Fix from @Donokami still needed on fresh install of Ubuntu Disco 19.04

**Comment by MattDaddy-Tries-YuKimmie** [comment]
Hi good people !!
Im running deepin 20.2  same issue like the others have stated. Komorebi doesnt start whatsoever 
i even tried running this command sudo ln -s /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.11.0.0 /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.10

but still doesnt open

**Comment by Kavinubuntu** [comment]
> Hi good people !!
> Im running deepin 20.2 same issue like the others have stated. Komorebi doesnt start whatsoever
> i even tried running this command sudo ln -s /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.11.0.0 /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.10
> 
> but still doesnt open

Yea im having the same problem im on ubuntu 20 whatever i just wanted to have a live wallpaper but i guess we can't have good things

**Comment by CrazyGamer007** [comment]
> > Hi good people !!
> > Im running deepin 20.2 same issue like the others have stated. Komorebi doesnt start whatsoever
> > i even tried running this command sudo ln -s /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.11.0.0 /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.10
> > but still doesnt open
> 
> Yea im having the same problem im on ubuntu 20 whatever i just wanted to have a live wallpaper but i guess we can't have good things
 I had the same Problem. The command is for an older version. Here is a new one: sudo ln -s /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.11.0.1 /usr/lib/x86_64-linux-gnu/libgtop-2.0.so.10

**Comment by tom8122** [comment]
> I install /opt/Komorebi via deb package and it's working!

Please tell me how can you able to do it this with proper ubuntu commands..
I am using ubuntu20.04
Please help, Komorebi can't be opened in my system..
